version: 1

build:
  os: "Qlik Sense 14.20.5"
  tools:
    python: "3.8"

sphinx:
  fail_on_warning: true    

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .  

formats:
  - pdf
  - epub      